#!/bin/bash

set -e

THIS_SCRIPT_DIR=$(readlink -f $(dirname $0))
TOP_DIR=$(readlink -f "${THIS_SCRIPT_DIR}/")


trap TRAP_CTRL_C INT

source "${TOP_DIR}/utils/bash_helpers.sh"


################################################################################
# Main function
################################################################################
function MAIN
{
    LOG_INFO "################################################################################"
    LOG_INFO "# "
    LOG_INFO "################################################################################"


    cd bsp/buildroot

    BSP_DIR=$(readlink -f "${THIS_SCRIPT_DIR}/bsp/")
    echo "# Autogenerated" > local.mk
    
    echo "LINUX_OVERRIDE_SRCDIR = ${BSP_DIR}/linux" >> local.mk
    echo "UBOOT_OVERRIDE_SRCDIR = ${BSP_DIR}/u-boot" >> local.mk

    make scope_defconfig
    make
}

################################################################################
#
################################################################################
function TRAP_CTRL_C() {
    LOG_ERROR "** Trapped CTRL-C"
    exit -1
}

MAIN

exit $?